name: E2E
# Когда запускаем
on:
  push:
    branches:
      - main
  workflow_dispatch:
# Описываем джобы
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Установка Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Установка пакетов
        run: npm i
      - name: Устанавливаем браузеры
        run: npx playwright install --with-deps
      - name: Запускаем тесты
        run: npm t
      - name: Запускаем генерацию allure в одном файле
        run: npm run allureFile
        if: always()
        continue-on-error: true
      # сохраняем результаты
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        continue-on-error: true
        with:
          name: allure-report
          path: allure-report
          retention-days: 30